remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: false
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
logo: /assets/Logo.jpeg
theme: jekyll-theme-minimal
